# Listener MQTT natif (TCP — pour simulateur, pont, clients Python)
listener 1883
allow_anonymous true
persistence true
persistence_location /mosquitto/data/

# Listener WebSocket (pour le frontend React via MQTT.js / WebSocket)
listener 9001
protocol websockets
allow_anonymous true